openapi: 3.1.0
info:
  title: Memorize Learn English - OpenAPI 3.1
  description: |-
    This is a backend of Memorize App

servers:
  - url: https://backend-memorize-learn-english-node-js.vercel.app/api/v1
tags:
  - name: Default
    description: Server Running Activities
  - name: Authentication
    description: Everything about Authentication

paths:
  /:
    get:
      summary: Server Running
      tags:
        - Default
      responses:
        "200":
          description: Server is running
  /health:
    get:
      summary: Health Check
      tags:
        - Default
      responses:
        "200":
          description: Server is healthy

  /auth/sign-up:
    post:
      summary: Sign Up
      description: Sign Up a user
      requestBody: { username: string, email: string, password: string }
      tags:
        - Authentication
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            example: 1234567890
                          name:
                            type: string
                            example: John Doe
                          email:
                            type: string
                            example: johndoe@example.com
                          avatar:
                            type: string
                            example: https://example.com/avatar.jpg
                          role:
                            type: string
                            example: user

    /auth/sign-in:
      post:
        summary: Sign In
        description: Sign In a user
        requestBody: { email: string, password: string }
        tags:
          - Authentication
        responses:
          "200":
            description: User logged in successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: User logged in successfully
                    data:
                      type: object
                      properties: 
                        user:
